api/urls.py
from django.urls import include, path
from rest_framework import routers

from api.views import BasketModelViewSet, ProductModelViewSet

app_name = 'api'

router = routers.DefaultRouter()
router.register(r'products', ProductModelViewSet)
router.register(r'baskets', BasketModelViewSet)


urlpatterns = [
    path('', include(router.urls)),
]

purchases/urls.py
from django.urls import path

from purchases.views import (CancelledTemplateView, PurchaseCreateView,
                             PurchaseDetailView, PurchaseListView,
                             SuccessTemplateView)

app_name = 'purchases'


urlpatterns = [
    path('place-order/', PurchaseCreateView.as_view(), name='place-order'),
    path('order-success/', SuccessTemplateView.as_view(), name='order-success'),
    path('order-cancelled/', CancelledTemplateView.as_view(), name='order-cancelled'),
    path('', PurchaseListView.as_view(), name='orders_list'),
    path('purchase/<int:pk>', PurchaseDetailView.as_view(), name='purchase'),
]

store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from rest_framework.authtoken.views import obtain_auth_token

from products.views import IndexView
from purchases.views import stripe_webhook_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('accounts/', include('allauth.urls')),
    path('purchases/', include('purchases.urls', namespace='purchases')),
    path('webhook/stripe/', stripe_webhook_view, name='stripe_webhook'),
    path('api/', include('api.urls', namespace='api')),
    path('api-token-auth/', obtain_auth_token)
]

if settings.DEBUG:
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls'))),
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

purchases/models.py
from django.db import models

from products.models import Basket
from users.models import User


# Create your models here.
class Purchase(models.Model):
    CREATED = 0
    PAID = 1
    ON_WAY = 2
    DELIVERED = 3
    STATUSES = (
        (CREATED, 'Created'),
        (PAID, 'Paid'),
        (ON_WAY, 'On way'),
        (DELIVERED, 'Delivered'),
      )

    firstname = models.CharField(max_length=64)
    lastname = models.CharField(max_length=64)
    email = models.EmailField(max_length=256)
    address = models.CharField(max_length=256)
    basket_history = models.JSONField(default=dict)
    created = models.DateField(auto_now_add=True)
    status = models.SmallIntegerField(default=CREATED, choices=STATUSES)
    initiator = models.ForeignKey(to=User, on_delete=models.CASCADE)

    def __str__(self):
        return f'Purchase #{self.id}: {self.firstname} {self.lastname}'

    class Meta:
        verbose_name = "Purchase"
        verbose_name_plural = "Purchases"

    def update_after_payment(self):
        baskets = Basket.objects.filter(user=self.initiator)
        self.status = self.PAID
        self.basket_history = {
            'purchased_items': [basket.de_json() for basket in baskets],
            'total_sum': float(baskets.total_sum()),
        }
        baskets.delete()
        self.save()

purchases/forms.py
from django import forms

from purchases.models import Purchase


class PurchaseForm(forms.ModelForm):
    firstname = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Firstname'}))
    lastname = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Lastname'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'you@example.com'}))
    address = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Country, City, '
                                                            'Street, House'}))

    class Meta:
        model = Purchase
        fields = ('firstname', 'lastname', 'email', 'address')

purchases/views.py
from http import HTTPStatus

import stripe
from django.conf import settings
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.decorators.csrf import csrf_exempt
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView

from products.models import Basket
from purchases.forms import PurchaseForm
from purchases.models import Purchase
from store.common.views import TitleMixin

stripe.api_key = settings.STRIPE_SECRET_KEY


class SuccessTemplateView(TitleMixin, TemplateView):
    template_name = 'purchases/success.html'
    title = 'Successful order'


class CancelledTemplateView(TemplateView):
    template_name = 'purchases/cancelled.html'


class PurchaseListView(TitleMixin, ListView):
    template_name = 'purchases/purchases.html'
    title = 'Orders'
    queryset = Purchase.objects.all()
    ordering = ['id']

    def get_queryset(self):
        queryset = super(PurchaseListView, self).get_queryset()
        return queryset.filter(initiator=self.request.user)


class PurchaseDetailView(DetailView):
    template_name = 'purchases/purchase.html'
    model = Purchase

    def get_context_data(self, **kwargs):
        context = super(PurchaseDetailView, self).get_context_data(**kwargs)
        context['title'] = f'Order # {self.object.id}'
        return context


class PurchaseCreateView(TitleMixin, CreateView):
    template_name = 'purchases/place-order.html'
    form_class = PurchaseForm
    success_url = reverse_lazy('purchases:place-order')
    title = 'Place order'

    def form_valid(self, form):
        form.instance.initiator = self.request.user
        return super(PurchaseCreateView, self).form_valid(form)

    def post(self, request, *args, **kwargs):
        super(PurchaseCreateView, self).post(request, *args, **kwargs)
        baskets = Basket.objects.filter(user=self.request.user)
        checkout_session = stripe.checkout.Session.create(
            line_items=baskets.stripe_products(),
            metadata={'order_id': self.object.id},
            mode='subscription',
            success_url='{}{}'.format(settings.DOMAIN_NAME, reverse('purchases:order-success')),
            cancel_url='{}{}'.format(settings.DOMAIN_NAME, reverse('purchases:order-cancelled')),
        )
        return HttpResponseRedirect(checkout_session.url, status=HTTPStatus.SEE_OTHER)

    def form_valid(self, form):
        form.instance.initiator = self.request.user
        return super(PurchaseCreateView, self).form_valid(form)


@csrf_exempt
def stripe_webhook_view(request):
    payload = request.body
    sig_header = request.META['HTTP_STRIPE_SIGNATURE']
    event = None

    try:
        event = stripe.Webhook.construct_event(
            payload, sig_header, settings.STRIPE_WEBHOOK_SECRET
        )
    except ValueError:
        # Invalid payload
        return HttpResponse(status=400)
    except stripe.error.SignatureVerificationError:
        # Invalid signature
        return HttpResponse(status=400)

    # Handle the checkout.session.completed event
    if event['type'] == 'checkout.session.completed':
        session = event['data']['object']

        # Fulfill the purchase...
        fulfill_order(session)

    # Passed signature verification
    return HttpResponse(status=200)


def fulfill_order(session):
    order_id = int(session.metadata.order_id)
    order = Purchase.objects.get(id=order_id)
    order.update_after_payment()

purchases/templates/purchases/cancelled.html
<!DOCTYPE html>
<html>
<head>
  <title>Checkout canceled</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <section>
    <p>Forgot to add something to your cart? Shop around then come back to pay!</p>
  </section>
</body>
</html>

purchases/templates/purchases/place-order.html
{% extends 'products/base.html' %}
{% load humanize %}

{% block content %}
<!-- Page Content -->
<section>
    <div class="alert alert-warning text-center" role="alert">
        Please enter email address.
    </div>
    <div class="container">
        <div class="py-5 text-center">
            <h1>Place order </h1>
        </div>
        <div class="row g-5">
            <div class="col-md-5 col-lg-4 order-md-last">
                <h4 class="d-flex justify-content-between align-items-center mb-3">
                    <span class="text-primary">Basket</span>
                    <span class="badge badge-primary badge-pill text-white">{{ baskets.total_quantity }}</span>
                </h4>
                <ul class="list-group mb-3">
                    {% for basket in baskets %}
                    <li class="list-group-item d-flex justify-content-between lh-sm">
                        <div>
                            <h6 class="my-0">
                                {{ basket.product.name }}
                            </h6>
                            <br>
                            Quantity: {{ basket.quantity }}
                        </div>
                        <span class="text-muted">{{ basket.sum|intcomma }} $</span>
                    </li>
                    {% endfor %}
                    <li class="list-group-item d-flex justify-content-between">
                        <h5>Total: </h5>
                        <h5>{{ baskets.total_sum|intcomma}} $</h5>
                    </li>

                </ul>
            </div>
            <div class="col-md-7 col-lg-8">
                <h4 class="mb-3">Delivery data</h4>
                <form action="{% url 'purchases:place-order' %}" method="post">
                    {% csrf_token %}
                    <div class="row g-3">
                        <div class="col-sm-6">
                            <label class="form-label" id="{{ form.firstname.id_for_label }}" for="{{ form.firstname.id_for_label }}">Firstname</label>
                                {{ form.firstname }}
                        </div>

                        <div class="col-sm-6">
                            <label class="form-label" id="{{ form.lastname.id_for_label }}" for="{{ form.lastname.id_for_label }}">Lastname</label>
                            {{ form.lastname }}
                        </div>

                        <div class="col-12 mt-3">
                            <label class="form-label" id="{{ form.email.id_for_label }}" for="{{ form.email.id_for_label }}">Email</label>
                            {{ form.email }}
                        </div>

                        <div class="col-12 mt-3">
                            <label class="form-label" id="{{ form.address.id_for_label }}" for="{{ form.address.id_for_label }}">Delivery address</label>
                            {{ form.address }}
                        </div>

                    </div>

                    <hr class="my-4">

                    <button class="w-100 btn btn-primary btn-lg" type="submit">Proceed to check out</button>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

purchases/templates/purchases/purchase.html
{% extends 'products/base.html' %}
{% load humanize %}
{% block content %}
<!-- Page Content -->
<section>
    <div class="container pt-5">
        <div class="text-center mt-5">
            <h1>Order#{{ object.id }}</h1>
            <div class="orders mt-5">
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">Name</th>
                        <th scope="col">Number</th>
                        <th scope="col">Price</th>
                        <th scope="col">Total price</th>
                    </tr>
                    </thead>
                    <tbody>

                    {% for purchased_item in object.basket_history.purchased_items %}
                    <tr>
                        <th scope="row">
                            {{ purchased_item.product_name }}
                        </th>
                        <td>{{ purchased_item.quantity }}</td>
                        <td>{{ purchased_item.price|intcomma }} $</td>
                        <td>{{ purchased_item.sum|intcomma }}</td>
                    </tr>
                    {% endfor %}

                    </tbody>
                </table>
                <p class="float-right h4 mt-3">Total price: {{ object.basket_history.total_sum|intcomma }}</p>
            </div>
        </div>
    </div>
</section>
{% endblock %}
<body>

purchases/templates/purchases/purchases.html
{% extends 'products/base.html' %}
{% load humanize %}

{% block content %}
<!-- Page Content -->
<section>
    <div class="container pt-5">
        <div class="text-center mt-5">
            <h1>Orders</h1>
            <div class="orders mt-5">
                <table class="table">
                    <thead>
                    <tr class="table-light">
                        <th scope="col">#</th>
                        <th scope="col">Status</th>
                        <th scope="col">Created</th>
                        <th scope="col">Total</th>
                        <th scope="col">Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for purchase in object_list %}
                    <tr>
                        <th scope="row">{{ purchase.id }} </th>
                        <td>{{ purchase.get_status_display }}</td>
                        <td>{{ purchase.created|naturalday }}</td>
                        <td>{{ purchase.basket_history.total_sum|intcomma }} $</td>
                        <td>
                            <a href="{% url 'purchases:purchase' purchase.id %}">View</a>
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
{% endblock %}

purchases/templates/purchases/success.html
{% extends 'users/base.html' %}

{% block content %}
<main>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                <div class="card shadow-lg border-0 rounded-lg mt-5">
                    <div class="card-header">
                        <h3 class="text-center font-weight-light my-4">Thank you for your order!</h3>
                    </div>
                    <div class="card-body text-center">
                        <h4>
                            Your order is successfully placed.
                        </h4>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}